"""initial schema

Revision ID: 0573499e6866
Revises: 
Create Date: 2026-05-30 15:12:08.739572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0573499e6866'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('default_unit', sa.String(length=40), nullable=False),
    sa.Column('default_form', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredients_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredients_slug'), ['slug'], unique=True)

    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('meal_type', sa.String(length=40), nullable=False),
    sa.Column('base_servings', sa.Integer(), nullable=False),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_meal_type'), ['meal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_slug'), ['slug'], unique=True)

    op.create_table('ingredient_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'label', name='uq_unit_ingredient_label')
    )
    with op.batch_alter_table('ingredient_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_units_ingredient_id'), ['ingredient_id'], unique=False)

    op.create_table('nutrition_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'form', name='uq_facts_ingredient_form')
    )
    with op.batch_alter_table('nutrition_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nutrition_facts_ingredient_id'), ['ingredient_id'], unique=False)

    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_label', sa.String(length=40), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_ingredient_id'))

    op.drop_table('recipe_ingredients')
    with op.batch_alter_table('nutrition_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nutrition_facts_ingredient_id'))

    op.drop_table('nutrition_facts')
    with op.batch_alter_table('ingredient_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_units_ingredient_id'))

    op.drop_table('ingredient_units')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_slug'))
        batch_op.drop_index(batch_op.f('ix_recipes_name'))
        batch_op.drop_index(batch_op.f('ix_recipes_meal_type'))

    op.drop_table('recipes')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_slug'))
        batch_op.drop_index(batch_op.f('ix_ingredients_name'))
        batch_op.drop_index(batch_op.f('ix_ingredients_category'))

    op.drop_table('ingredients')
    # ### end Alembic commands ###
