"""add source column to ingredients and recipes

Revision ID: 4e8f033ff937
Revises: 0573499e6866
Create Date: 2026-05-30 16:03:50.681192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8f033ff937'
down_revision: Union[str, None] = '0573499e6866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='seed'))
        batch_op.create_index(batch_op.f('ix_ingredients_source'), ['source'], unique=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=False, server_default='seed'))
        batch_op.create_index(batch_op.f('ix_recipes_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_source'))
        batch_op.drop_column('source')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredients_source'))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
